/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

/**
 *
 * @author ASUS
 */
//import java.sql.SQLException;
//import java.sql.Statement;
//import java.sql.ResultSet;
import javax.swing.JOptionPane;
//import javax.swing.*;
//import javax.swing.table.DefaultTableModel;
import java.sql.*;
public class add extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descfield = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        titlefield = new javax.swing.JTextField();
        prioritylist = new javax.swing.JComboBox<>();
        statuslist = new javax.swing.JComboBox<>();
        datefield = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setBackground(new java.awt.Color(255, 249, 249));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        descfield.setViewportView(jTextArea1);

        getContentPane().add(descfield);
        descfield.setBounds(460, 320, 370, 106);

        titlefield.setBackground(new java.awt.Color(255, 249, 249));
        titlefield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(titlefield);
        titlefield.setBounds(460, 270, 370, 30);

        prioritylist.setBackground(new java.awt.Color(255, 249, 249));
        prioritylist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prioritylist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));
        getContentPane().add(prioritylist);
        prioritylist.setBounds(460, 450, 370, 30);

        statuslist.setBackground(new java.awt.Color(255, 249, 249));
        statuslist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statuslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Completed" }));
        statuslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuslistActionPerformed(evt);
            }
        });
        getContentPane().add(statuslist);
        statuslist.setBounds(460, 620, 370, 30);

        datefield.setBackground(new java.awt.Color(255, 249, 249));
        datefield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(datefield);
        datefield.setBounds(460, 530, 370, 30);

        savebutton.setBackground(new java.awt.Color(104, 69, 117));
        savebutton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        savebutton.setForeground(new java.awt.Color(255, 249, 249));
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(savebutton);
        savebutton.setBounds(490, 710, 190, 40);

        backbutton.setBackground(new java.awt.Color(104, 69, 117));
        backbutton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        backbutton.setForeground(new java.awt.Color(255, 249, 249));
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(250, 710, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/add.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1120, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statuslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuslistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statuslistActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
  
 this.dispose();  // Close this "Add Task" window
home homeWindow = new home();  // Create a new instance of the home screen
   
    // Ensure the home screen is visible again
    
        homeWindow.setVisible(false);  // Make the existing home screen window visible
    
    homeWindow.setSize(1170,800); // Optional: Set size if not already set in the 'home' class
    homeWindow.setLocationRelativeTo(null); // Center the JFrame on the screen
    homeWindow.setVisible(true);
       
      
    }//GEN-LAST:event_backbuttonActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
           String title = titlefield.getText();
    String description = jTextArea1.getText();
    String dueDate = datefield.getText();
    String priority = (String) prioritylist.getSelectedItem();
    String status = (String) statuslist.getSelectedItem();

    // Validate input fields
    if (title.isEmpty() || dueDate.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Title and Due Date are required fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Database logic
    DatabaseConnection dbConnection = new DatabaseConnection();
    try (Connection conn = dbConnection.getConnection()) {
        // Insert query
        String query = "INSERT INTO tasks (title, description, priority, due_date, status) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, title);
        pst.setString(2, description);
        pst.setString(3, priority);
        pst.setString(4, dueDate);
        pst.setString(5, status);

        // Execute the query
        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Task added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            // Optionally, clear the fields after successful insertion
            titlefield.setText("");
            jTextArea1.setText("");
            datefield.setText("");
            prioritylist.setSelectedIndex(0);
            statuslist.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add the task.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error while saving the task: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_savebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField datefield;
    private javax.swing.JScrollPane descfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> prioritylist;
    private javax.swing.JButton savebutton;
    private javax.swing.JComboBox<String> statuslist;
    private javax.swing.JTextField titlefield;
    // End of variables declaration//GEN-END:variables
}
