/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

/**
 *
 * @author ASUS
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getstartedbtn = new javax.swing.JButton();
        statbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        getstartedbtn.setBackground(new java.awt.Color(104, 69, 117));
        getstartedbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        getstartedbtn.setForeground(new java.awt.Color(255, 249, 249));
        getstartedbtn.setText("Get Started");
        getstartedbtn.setBorderPainted(false);
        getstartedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getstartedbtnActionPerformed(evt);
            }
        });
        getContentPane().add(getstartedbtn);
        getstartedbtn.setBounds(360, 510, 180, 50);
        getstartedbtn.getAccessibleContext().setAccessibleName("getstartedbtn");

        statbtn.setBackground(new java.awt.Color(104, 60, 117));
        statbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        statbtn.setForeground(new java.awt.Color(255, 249, 249));
        statbtn.setText("My Progress");
        statbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statbtnActionPerformed(evt);
            }
        });
        getContentPane().add(statbtn);
        statbtn.setBounds(160, 510, 180, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 700, 640);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 480, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getstartedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getstartedbtnActionPerformed
        // TODO add your handling code here:
      home homeFrame = new home();
    homeFrame.setSize(1170,800); // Optional: Set size if not already set in the 'home' class
    homeFrame.setLocationRelativeTo(null); // Center the JFrame on the screen
    homeFrame.setVisible(true);

    // Close the current JFrame
    this.dispose();// Close the current JFrame
    }//GEN-LAST:event_getstartedbtnActionPerformed

    private void statbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statbtnActionPerformed
        // TODO add your handling code here:
        
        Dashboardnew dashboard = new Dashboardnew();
dashboard.setSize(820, 620);
dashboard.setLocationRelativeTo(null); // Center the JFrame
dashboard.setVisible(true);
 // Optional: Close the current frame

    }//GEN-LAST:event_statbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            main frame = new main();
            frame.setSize(720,620); // Set the size of the JFrame to 520x520
            frame.setLocationRelativeTo(null); // Center the JFrame on the screen
            frame.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getstartedbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton statbtn;
    // End of variables declaration//GEN-END:variables
}
